# Generated by Django 3.1 on 2020-08-13 19:50

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20200813_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='source_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(blog.models.get_deleted_user_instance), related_name='author_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
