# Generated by Django 3.1 on 2020-08-19 04:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_profilepicture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilePicture',
            new_name='UserProfile',
        ),
    ]
