# Generated by Django 3.1 on 2020-08-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_photo_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='imagename',
            field=models.CharField(max_length=100),
        ),
    ]
