# Generated by Django 3.1 on 2020-08-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200820_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='imagename',
            new_name='description',
        ),
    ]
