# Generated by Django 3.1 on 2020-08-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200820_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='postphoto',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Photo to upload'),
        ),
    ]
