# Generated by Django 3.1 on 2020-08-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200820_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.Photo'),
        ),
    ]
